name: ci
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os-name }}-latest
    strategy:
      matrix:
        os-name: [ ubuntu, windows, macos ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: build
        shell: bash
        run: |
          dotnet build